name: Full CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre_checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: "3.13"

      - name: Set up Rye
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"

      - name: Install deps & build base images
        run: make setup

      - name: Check format
        run: make check_format

      - name: Check linting
        run: make check_linting

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false # Do not stop when any job fails
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Set up Rye
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"

      - name: Install deps & build base images
        run: make setup

      - name: Run the tests
        run: make test
